# Generated by Django 4.2.16 on 2026-04-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0004_detallepedido_entregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0002_producto_requiere_cocina'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Ingrediente',
                'verbose_name_plural': 'Categorías de Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('unidad', 'Unidades'), ('porcion', 'Porciones')], default='unidad', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_critico', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='inventario.categoriaingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de stock'), ('salida_pedido', 'Consumo por pedido'), ('devolucion_pedido', 'Devolución de pedido'), ('ajuste_manual', 'Ajuste manual')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_resultante', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.ingrediente')),
                ('referencia_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='pedidos.detallepedido')),
                ('referencia_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_recetas', to='inventario.ingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'unique_together': {('producto', 'ingrediente')},
            },
        ),
    ]
